// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"oil/config"
	"oil/infras/jwt"
	"oil/infras/otel"
	"oil/infras/postgres"
	"oil/infras/redis"
	service2 "oil/internal/domains/auth/service"
	"oil/internal/domains/todo/repository"
	"oil/internal/domains/todo/service"
	repository2 "oil/internal/domains/user/repository"
	"oil/internal/handlers/auth"
	"oil/internal/handlers/todo"
	"oil/permissions"
	"oil/shared/cache"
	"oil/transport/http"
	"oil/transport/http/middleware"
	"oil/transport/http/router"
)

// Injectors from wire.go:

func InitializeService() *http.HTTP {
	configConfig := config.Get()
	connection := postgres.New(configConfig)
	otelOtel := otel.New(configConfig)
	repositoryTodo := repository.New(connection, otelOtel)
	client := redis.New(configConfig)
	redisCache := cache.NewRedisCache(client, otelOtel)
	serviceTodo := service.New(repositoryTodo, configConfig, redisCache, otelOtel)
	handler := todo.New(serviceTodo, otelOtel)
	user := repository2.New(connection, otelOtel)
	jwtJWT := jwt.New(configConfig, redisCache)
	serviceAuth := service2.New(user, configConfig, otelOtel, jwtJWT)
	authHandler := auth.New(serviceAuth, otelOtel)
	domainHandlers := router.DomainHandlers{
		Todo: handler,
		Auth: authHandler,
	}
	routerRouter := router.New(domainHandlers)
	appMiddleware := middleware.NewAppMiddleware(otelOtel, configConfig, redisCache)
	permissionData := permissions.Get()
	authRole := middleware.NewAuthRoleMiddleware(jwtJWT, otelOtel, permissionData, configConfig)
	httpHTTP := http.New(configConfig, routerRouter, connection, appMiddleware, authRole)
	return httpHTTP
}

// wire.go:

var configurations = wire.NewSet(config.Get, permissions.Get)

var infrastructures = wire.NewSet(postgres.New, otel.New, redis.New, jwt.New)

var middlewares = wire.NewSet(middleware.NewAppMiddleware, middleware.NewAuthRoleMiddleware)

var sharedHelpers = wire.NewSet(cache.NewRedisCache)

var todoDomain = wire.NewSet(repository.New, service.New)

var authDomain = wire.NewSet(repository2.New, service2.New)

var domains = wire.NewSet(
	todoDomain,
	authDomain,
)

var routing = wire.NewSet(wire.Struct(new(router.DomainHandlers), "*"), todo.New, auth.New, router.New)
