// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"oil/config"
	"oil/internal/handlers/test"
	"oil/transport/http"
	"oil/transport/http/router"
)

// Injectors from wire.go:

func InitializeService() *http.HTTP {
	configConfig := config.Get()
	handler := test.New()
	domainHandlers := router.DomainHandlers{
		Test: handler,
	}
	routerRouter := router.New(domainHandlers)
	httpHTTP := http.New(configConfig, routerRouter)
	return httpHTTP
}

// wire.go:

var configurations = wire.NewSet(config.Get)

var routing = wire.NewSet(wire.Struct(new(router.DomainHandlers), "*"), test.New, router.New)
